/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LePoint_BAT (https://sketchfab.com/LePointBAT)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toon-japan-honda-nsx-d8bb76afe9c14a7ebe424b9c2ae178e3
Title: TOON Japan : Honda NSX
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Nsx(props) {
  const { nodes, materials } = useGLTF('/models/toon_japan__honda_nsx.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.209, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Paint} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.White_Lights} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Red_Lights} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Interior} />
        <group position={[0.71, -0.091, -0.343]}>
          <mesh geometry={nodes.Object_13.geometry} material={materials.Disk} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.Tire} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Rims} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Caliper} />
        </group>
        <group position={[0.684, -0.091, 0.329]}>
          <mesh geometry={nodes.Object_18.geometry} material={materials.Disk} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.Tire} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.Rims} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.Caliper} />
        </group>
        <group position={[0.93, -0.015, -0.008]} scale={0.1}>
          <mesh geometry={nodes.Object_23.geometry} material={materials.Black} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Paint} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.White_Lights} />
        </group>
        <group position={[0, -0.209, 0]}>
          <mesh geometry={nodes.Object_27.geometry} material={materials.Disk} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.Tire} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.Rims} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.Caliper} />
        </group>
      </group>
    </group>
  )
}



useGLTF.preload('/models/toon_japan__honda_nsx.glb')
